version: '3.9'
services:
  solver:
    image: maven:3.8.6-eclipse-temurin-17
    container_name: solver
    working_dir: /workspace
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./solver:/workspace:cached
      - ~/.m2:/root/.m2
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    command: mvn spring-boot:run
  
  db:
    container_name: db
    image: mongo:8
    restart: always
    ports:
      - 27017:27017
    tty: true
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: shiftplanner_solver
      TZ: Asia/Tokyo

  web:
    container_name: web
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./web/shiftplanner:/usr/share/nginx/html:cached
      - ./web/config/nginx.conf:/etc/nginx/conf.d/default.conf
    tty: true
    depends_on:
      - solver
