services:
  solver:
    image: maven:3.8.6-eclipse-temurin-17
    container_name: solver
    working_dir: /workspace
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./solver:/workspace:cached
      - ~/.m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/solver-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${ENVIRONMENT}
    depends_on:
      - db
    command: mvn spring-boot:run
  
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: solver-db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

  web:
    container_name: web
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./web/shiftplanner:/usr/share/nginx/html:cached
      - ./web/config/nginx.conf:/etc/nginx/conf.d/default.conf
    tty: true
    depends_on:
      - solver

volumes:
  mysql-data: